### ISSUE TITLE
Consider adding a type definition for Typescript

### ISSUE THREAD

**Issue by djey47** [jdanigo/tailwind-toastify#1]
Hello,

I think it would be great to provide a type def for Typescript. As in current state this module has no available defs.

```typescript
import { showAlert } from 'tailwind-toastify';
```
, results in following TS error:

```
Could not find a declaration file for module 'tailwind-toastify'. '/<...>/node_modules/tailwind-toastify/build/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/tailwind-toastify` if it exists or add a new declaration (.d.ts) file containing `declare module 'tailwind-toastify
```

It may be solved by adding a d.ts file in every project, but providing it from the lib would be a plus.

**Comment by jdanigo** [comment]
Hello, thanks for you comment, I wanted to do a pilot test, if this was useful to someone else, since you already made the first comment about making improvements, I will start with the implementation of the second version, which includes TS and some improvements, to keep the DOM much cleaner.

**Comment by djey47** [comment]
Great, I will use a workaround till the second version comes. Thanks!

**Comment by djey47** [comment]
FWIW, I'll drop a def here to be used as a workaround:

```typescript
declare module 'tailwind-toastify' {
  function showAlert(type: 'info' | 'error' | 'success', title: string, message: string): void;
  export { showAlert };
}
```

**Comment by jdanigo** [comment]
Thank you for report a issue, this is npm package update now.

**Comment by djey47** [comment]
Just updated to 1.0.8 and it's working like a charm, thanks!
